# k8s-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mmhello-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mmhello
  template:
    metadata:
      labels:
        app: mmhello
    spec:
      containers:
      - name: mmhello
        image: mmhello:latest
        ports:
        - containerPort: 5000
        imagePullPolicy: Never
---

apiVersion: v1
kind: Service
metadata:
  name: mmhello-service
spec:
  type: NodePort
  selector:
    app: mmhello
  ports:
  - protocol: TCP
    name: http
    port: 5000
    nodePort: 30007
