apiVersion: v1
kind: Service
metadata:
  name: mmhello-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: mmhello
  ports:
    - protocol: TCP
      name: http
      port: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}

