replicaCount: 2

image:
  repository: mmhello
  tag: latest
  pullPolicy: Never

service:
  type: NodePort
  port: 5000
  nodePort: 30007

serviceAccount:
  create: true
  # other settings for the service account...


